spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    properties:
      show_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG


eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/